# Generated by Django 6.0.5 on 2026-05-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angular', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angular',
            name='content_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('updated', 'Updated'), ('archived', 'Archived')], default='pending', max_length=50),
        ),
    ]
