# Generated by Django 6.0.5 on 2026-05-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angular', '0002_alter_angular_content_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angular',
            name='content_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('updated', 'Updated'), ('archived', 'Archived')], default='pending'),
        ),
    ]
